@startuml

class CV {}

class ContentLayer {}

class Content {
  name
  description
  url
}

class File {
  path
  type
}

class SectionLayer {}

class Section {
  name // UNIQUE
}

' || IdSection

class IdentificationSection {}

class Contact {
  type
  info
}

class Language {
  name
  conversation
  reading
  writing
  comprehension
  peerReview
}

class Person {
  name
  gender
  title
  birthDate
  picture
  maritalStatus
  aboutMe
}

class Address {
  name
  line1
  line2
  postalCode
  city
  country
}

class Nationality {
  name
}

class Investigator {
  citationName
}

class AuthorId {
  name
  info
}

' || END IdSection

' || WorkExperienceSection

class WorkExperienceSection {
}

class WorkExperience {
  occupation
  employer
  description
}

class TimeFrame {
  startDate
  endDate
}

' || END WorkExperienceSection

' || EducationTrainingSection
class EducationTrainingSection {
}

class EducationTraining {
  title
  organization
  description
  finalGrade
}

enum FieldOfStudy {
  GENERIC /' generic programs and classifications '/
  EDUCATION /' Education '/
  ARTS_HUMANITIES /' Arts and humanities '/
  SOCIAL_SCIENCES /' Social sciences, journalism and information '/
  BUSINESS_LAW /' Business, administration and law '/
  NATURAL_SCIENCES /' Natural sciences, mathematics and statistics '/
  INFO_COMM_TECH /' Information and Communication Technologies '/
  ENGINEERING /' Engineering, manufacturing and construction '/
  AGRICULTURE /' Agriculture, forestry, fisheries and veterinary '/
  HEALTH /' Health and welfare '/
  SERVICES /' Services '/
  UNKNOWN /' Field unknown '/
}

enum EQF {
  EQF1
  EQF2
  EQF3
  EQF4
  EQF5
  EQF6
  EQF7
  EQF8
}

' || END EducationTrainingSection

ContentLayer -u-* CV
SectionLayer -u-* CV

ContentLayer -d-> "*" Content
Content --> "0..1" TimeFrame
Content --> "*" File

SectionLayer --> IdentificationSection : "PersonId"
Section --> "1..*" Content
Section "*" -u-* SectionLayer
Section "0..1" -d-> "*" Section : "Sub-section"

IdentificationSection -u-|> Section
' CV -d-> "1" Section : "Identification"
IdentificationSection --> Person

Person --> "*" Contact
Person --> "*" Nationality
Person --> "*" Address
Person -r-> "*" Language

Investigator -u-|> Person
Investigator -r-> "*" AuthorId

WorkExperienceSection -u-|> Section
WorkExperienceSection -d-> "1..*" WorkExperience
WorkExperience --> "0..1" Address
WorkExperience --> TimeFrame

EducationTraining --|> Section
EducationTrainingSection --> EducationTraining
EducationTraining --> Address
EducationTraining --> TimeFrame
EducationTraining --> "0..1" FieldOfStudy
EducationTraining --> "0..1" EQF

@enduml
